name: Test
on:
  pull_request:
  push: { branches: main }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build environment
      run: |
        sudo apt-get update                      && \
        sudo apt-get upgrade -y                  && \
        sudo apt-get install -y less wget        && \
        sudo apt-get install -y build-essential  && \
        sudo apt-get install -y libdancer-perl

    - name: Run docker image with entrypoint
      run: perl app.pl &

    - name: Run curl to ensure endpoint responds
      run: curl -i http://127.0.0.1:3000
