name: Test
on:
  pull_request:
  push: { branches: main }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker image
      run: docker build -t dancer .

    - name: Run docker image with entrypoint
      run: docker run -d dancer

    - name: Validate container
      run: docker container ls

    - name: Run curl to ensure endpoint responds
      run: curl -i http://127.0.0.1:3001
